version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: savojimahdi/vprofile-project-db:1.0.0
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  vproapp:
    build: 
      context: ./Docker-files/app
    image: savojimahdi/vprofile-project-app:1.0.0
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    
  vproweb:
    build: 
      context: ./Docker-files/web
    image: savojimahdi/vprofile-project-web:1.0.0
    container_name: vproweb
    ports:
      - "80:80"

volumes:
   vprodbdata: {}
   vproappdata: {}
